ip = { default = "localhost", doc = "connection URL", env = "IP" }
port = { type = "usize", default = "8080", doc = "Server port number", env = "PORT" }
pwd = { default = "changeme", doc = "masked password",  secret = true }
pwd_r = { default = "changeme", optional= true, doc = "masked password",  secret = true }
pwd_int = { default = "123",  doc = "masked password",  secret = true, type = "Int" }
