ip = { default = "localhost", doc = "connection URL", env = "IP" }
port = { type = "int", default = "8080", doc = "Server port number", env = "PORT" }
enum1 = { enum = "Enum1", variants = [
  "A",
  "B",
  "C",
], default = "A", doc = "An example enum", env = "ENUM1" }
enum2 = { enum = "MyEnum", doc = "An example enum", env = "ENUM2", default = "C" }
