port = { type = "u16", default = "8080", doc = "Server port number", env = "PORT" }
url = { default = "localhost", env = "URL" }
[redis]
doc = "Redis configuration"
url = { default = "redis://localhost:6379", doc = "Redis connection URL", env = "REDIS_URL" }
pool_size = { type = "u32", default = "10", doc = "Connection pool size", env = "REDIS_POOL_SIZE" }
