port = { type = "u16", default = "8080", doc = "Server port number", env = "PORT" }
id = { type = "u16", default = "2", doc = "Server id number", env = "ID", optional = true }
o = { env = "O", optional = true }
s2 = { env = "O", default = "true" }
