port = { type = "u16", default = "8080", doc = "Server port number", env = "PORT" }
id = { type = "u16", default = "2", doc = "Server id number", env = "ID", optional = true }
o = { env = "O", optional = true }
s2 = { env = "O", default = "true" }
s3 = { type = "bool", env = "O", default = "true" }
[redis]
doc = "Redis configuration"
url = { type = "String", default = "redis://localhost:6379", doc = "Redis connection URL", env = "REDIS_URL" }
pool_size = { type = "u32", default = "10", doc = "Connection pool size", env = "REDIS_POOL_SIZE" }
port = { type = "u16", default = "8080", env = "PORT", short = "p", long = "port2" }
