small_int = { type = "int", default = "80" }
int = { type = "int", default = "8000" }
float = { type = "float", default = "90.80" }
boolean = { type = "bool", default = "true" }
string = { type = "string", default = "string_value" }
path = { type = "path", default = "." }
