array = { type = "[char]", default = ['A', 'B', 'C'], env = "ABC" }
array2 = { type = "[int]", default = [1, 2, 3], env = "AB" }
# enumeration = { type = "char", value = ['A', 'B', 'C'], env = "ABC" }
port = { type = "int", default = "9080" }
id = { type = "int", default = "2" }
