[workspace.package]
description = "Static clap macro generator"
authors = ["Slim Ouertani"]

[workspace]
members = ["example", "rclap_core", "rclap_derive"]

resolver = "3"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
[workspace.dependencies]
