name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-action@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-action@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build

  build-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-action@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --features secret

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-action@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test

  test-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-action@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --features secret
